package databaseAccess;

// Generated 24/Set/2015 16:00:24 by Hibernate Tools 3.4.0.CR1

/**
 * Association generated by hbm2java
 */
public class Association implements java.io.Serializable {

	private Integer id;
	private ProteinList proteinList;
	private String type;

	public Association() {
	}

	public Association(ProteinList proteinList, String type) {
		this.proteinList = proteinList;
		this.type = type;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ProteinList getProteinList() {
		return this.proteinList;
	}

	public void setProteinList(ProteinList proteinList) {
		this.proteinList = proteinList;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
