package databaseAccess;

// Generated 24/Set/2015 16:00:24 by Hibernate Tools 3.4.0.CR1

/**
 * ProteinAlias generated by hbm2java
 */
public class ProteinAlias implements java.io.Serializable {

	private Integer id;
	private ProteinList proteinList;
	private String alias;
	private String type;

	public ProteinAlias() {
	}

	public ProteinAlias(ProteinList proteinList, String alias, String type) {
		this.proteinList = proteinList;
		this.alias = alias;
		this.type = type;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ProteinList getProteinList() {
		return this.proteinList;
	}

	public void setProteinList(ProteinList proteinList) {
		this.proteinList = proteinList;
	}

	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
