package databaseAccess;

// Generated 24/Set/2015 16:00:24 by Hibernate Tools 3.4.0.CR1

/**
 * ProteinInTf generated by hbm2java
 */
public class ProteinInTf implements java.io.Serializable {

	private Integer id;
	private ProteinList proteinList;
	private TfSet tfSet;

	public ProteinInTf() {
	}

	public ProteinInTf(ProteinList proteinList, TfSet tfSet) {
		this.proteinList = proteinList;
		this.tfSet = tfSet;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ProteinList getProteinList() {
		return this.proteinList;
	}

	public void setProteinList(ProteinList proteinList) {
		this.proteinList = proteinList;
	}

	public TfSet getTfSet() {
		return this.tfSet;
	}

	public void setTfSet(TfSet tfSet) {
		this.tfSet = tfSet;
	}

}
