package databaseAccess;

// Generated 24/Set/2015 16:00:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ProteinList generated by hbm2java
 */
public class ProteinList implements java.io.Serializable {

	private Integer id;
	private String entrezGeneId;
	private String geneSymbol;
	private String species;
	private Set proteinAliases = new HashSet(0);
	private Set proteinInStemnessSignatureses = new HashSet(0);
	private Set associations = new HashSet(0);
	private Set proteinInTfs = new HashSet(0);

	public ProteinList() {
	}

	public ProteinList(String entrezGeneId, String species) {
		this.entrezGeneId = entrezGeneId;
		this.species = species;
	}

	public ProteinList(String entrezGeneId, String geneSymbol, String species,
			Set proteinAliases, Set proteinInStemnessSignatureses,
			Set associations, Set proteinInTfs) {
		this.entrezGeneId = entrezGeneId;
		this.geneSymbol = geneSymbol;
		this.species = species;
		this.proteinAliases = proteinAliases;
		this.proteinInStemnessSignatureses = proteinInStemnessSignatureses;
		this.associations = associations;
		this.proteinInTfs = proteinInTfs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEntrezGeneId() {
		return this.entrezGeneId;
	}

	public void setEntrezGeneId(String entrezGeneId) {
		this.entrezGeneId = entrezGeneId;
	}

	public String getGeneSymbol() {
		return this.geneSymbol;
	}

	public void setGeneSymbol(String geneSymbol) {
		this.geneSymbol = geneSymbol;
	}

	public String getSpecies() {
		return this.species;
	}

	public void setSpecies(String species) {
		this.species = species;
	}

	public Set getProteinAliases() {
		return this.proteinAliases;
	}

	public void setProteinAliases(Set proteinAliases) {
		this.proteinAliases = proteinAliases;
	}

	public Set getProteinInStemnessSignatureses() {
		return this.proteinInStemnessSignatureses;
	}

	public void setProteinInStemnessSignatureses(
			Set proteinInStemnessSignatureses) {
		this.proteinInStemnessSignatureses = proteinInStemnessSignatureses;
	}

	public Set getAssociations() {
		return this.associations;
	}

	public void setAssociations(Set associations) {
		this.associations = associations;
	}

	public Set getProteinInTfs() {
		return this.proteinInTfs;
	}

	public void setProteinInTfs(Set proteinInTfs) {
		this.proteinInTfs = proteinInTfs;
	}

}
