package databaseAccess;

// Generated 24/Set/2015 16:00:24 by Hibernate Tools 3.4.0.CR1

/**
 * PubmedRefs generated by hbm2java
 */
public class PubmedRefs implements java.io.Serializable {

	private Integer id;
	private StemnessSignatures stemnessSignatures;
	private int pubmedid;

	public PubmedRefs() {
	}

	public PubmedRefs(StemnessSignatures stemnessSignatures, int pubmedid) {
		this.stemnessSignatures = stemnessSignatures;
		this.pubmedid = pubmedid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public StemnessSignatures getStemnessSignatures() {
		return this.stemnessSignatures;
	}

	public void setStemnessSignatures(StemnessSignatures stemnessSignatures) {
		this.stemnessSignatures = stemnessSignatures;
	}

	public int getPubmedid() {
		return this.pubmedid;
	}

	public void setPubmedid(int pubmedid) {
		this.pubmedid = pubmedid;
	}

}
