package databaseAccess;

// Generated 24/Set/2015 16:00:24 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * StemnessSignatures generated by hbm2java
 */
public class StemnessSignatures implements java.io.Serializable {

	private Integer id;
	private String name;
	private String type;
	private String description;
	private String sample;
	private String platform;
	private String species;
	private String source;
	private String publicationTitle;
	private String publicationAbstract;
	private String cellType;
	private String summary;
	private Set pubmedRefses = new HashSet(0);
	private Set proteinInStemnessSignatureses = new HashSet(0);

	public StemnessSignatures() {
	}

	public StemnessSignatures(String name, String type, String species) {
		this.name = name;
		this.type = type;
		this.species = species;
	}

	public StemnessSignatures(String name, String type, String description,
			String sample, String platform, String species, String source,
			String publicationTitle, String publicationAbstract,
			String cellType, String summary, Set pubmedRefses,
			Set proteinInStemnessSignatureses) {
		this.name = name;
		this.type = type;
		this.description = description;
		this.sample = sample;
		this.platform = platform;
		this.species = species;
		this.source = source;
		this.publicationTitle = publicationTitle;
		this.publicationAbstract = publicationAbstract;
		this.cellType = cellType;
		this.summary = summary;
		this.pubmedRefses = pubmedRefses;
		this.proteinInStemnessSignatureses = proteinInStemnessSignatureses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getSample() {
		return this.sample;
	}

	public void setSample(String sample) {
		this.sample = sample;
	}

	public String getPlatform() {
		return this.platform;
	}

	public void setPlatform(String platform) {
		this.platform = platform;
	}

	public String getSpecies() {
		return this.species;
	}

	public void setSpecies(String species) {
		this.species = species;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getPublicationTitle() {
		return this.publicationTitle;
	}

	public void setPublicationTitle(String publicationTitle) {
		this.publicationTitle = publicationTitle;
	}

	public String getPublicationAbstract() {
		return this.publicationAbstract;
	}

	public void setPublicationAbstract(String publicationAbstract) {
		this.publicationAbstract = publicationAbstract;
	}

	public String getCellType() {
		return this.cellType;
	}

	public void setCellType(String cellType) {
		this.cellType = cellType;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public Set getPubmedRefses() {
		return this.pubmedRefses;
	}

	public void setPubmedRefses(Set pubmedRefses) {
		this.pubmedRefses = pubmedRefses;
	}

	public Set getProteinInStemnessSignatureses() {
		return this.proteinInStemnessSignatureses;
	}

	public void setProteinInStemnessSignatureses(
			Set proteinInStemnessSignatureses) {
		this.proteinInStemnessSignatureses = proteinInStemnessSignatureses;
	}

}
