package databaseAccess;

// Generated 24/Set/2015 16:00:24 by Hibernate Tools 3.4.0.CR1

/**
 * TfPubmedRefs generated by hbm2java
 */
public class TfPubmedRefs implements java.io.Serializable {

	private Integer id;
	private TfSet tfSet;
	private Integer pubmedid;

	public TfPubmedRefs() {
	}

	public TfPubmedRefs(TfSet tfSet) {
		this.tfSet = tfSet;
	}

	public TfPubmedRefs(TfSet tfSet, Integer pubmedid) {
		this.tfSet = tfSet;
		this.pubmedid = pubmedid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TfSet getTfSet() {
		return this.tfSet;
	}

	public void setTfSet(TfSet tfSet) {
		this.tfSet = tfSet;
	}

	public Integer getPubmedid() {
		return this.pubmedid;
	}

	public void setPubmedid(Integer pubmedid) {
		this.pubmedid = pubmedid;
	}

}
